### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/client/KeyMapping

### ISSUE THREAD

**Issue by fiddleplum** [UnRealDinnerbone/SimpleZoom#7]
I saw the previous closed issues, but thought I'd mention it's still showing up in the latest iteration. Let me know if you need more info about my system.

Minecraft version: 1.16.5
SimpleZoom file: simplezoom-2.4.17+mc-1.16.5-dev.jar
Forge file: forge-1.16.5-36.1.25-installer.jar

(downloaded the latest of all of them today Jun 4, 2021)

Relevant part of the log:

```
java.lang.NoClassDefFoundError: net/minecraft/client/KeyMapping
	at com.unrealdinnerbone.simplezoom.SimpleZoomClient.<init>(SimpleZoomClient.java:31) ~[?:2.4.17+mc-1.16.5]
	at com.unrealdinnerbone.simplezoom.SimpleZoom.lambda$null$0(SimpleZoom.java:37) ~[?:2.4.17+mc-1.16.5]
	at com.unrealdinnerbone.simplezoom.SimpleZoom$$Lambda$3222/706977917.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:125) ~[?:?]
	at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:109) ~[?:?]
	at com.unrealdinnerbone.simplezoom.SimpleZoom.<init>(SimpleZoom.java:36) ~[?:2.4.17+mc-1.16.5]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) [?:36.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3111/1552133633.run(Unknown Source) [?:36.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3139/2009215919.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.KeyMapping
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 21 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
		at com.unrealdinnerbone.simplezoom.SimpleZoomClient.<init>(SimpleZoomClient.java:31) ~[?:2.4.17+mc-1.16.5]
		at com.unrealdinnerbone.simplezoom.SimpleZoom.lambda$null$0(SimpleZoom.java:37) ~[?:2.4.17+mc-1.16.5]
		at com.unrealdinnerbone.simplezoom.SimpleZoom$$Lambda$3222/706977917.run(Unknown Source) ~[?:?]
		at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:125) ~[?:?]
		at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:109) ~[?:?]
		at com.unrealdinnerbone.simplezoom.SimpleZoom.<init>(SimpleZoom.java:36) ~[?:2.4.17+mc-1.16.5]
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
		at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) [?:36.1]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3111/1552133633.run(Unknown Source) [?:36.1]
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) [?:?]
		at net.minecraftforge.fml.ModContainer$$Lambda$3139/2009215919.run(Unknown Source) [?:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
```

**Comment by Wachecheiro** [comment]
same error here

**Comment by UnRealDinnerbone** [comment]
Hopefully new version that should be out soon fixes this...
